### ISSUE TITLE
GET request with parameters

### ISSUE THREAD

**Issue by Vintorez** [astaxie/bat#13]
I tried to send a GET request with parameters, as in your example.
```
$ bat GET www.google.com search=bat tbm=isch
```
But actually I had the following request:
```
GET / HTTP/1.1
```
It seems that the request body is empty.
This "params" variable is always empty for me (map[]) https://github.com/astaxie/bat/blob/master/httplib/httplib.go#L355
Am I doing something wrong?

**Comment by astaxie** [comment]
@Vintorez please update the bat, it's a bug.

**Comment by Vintorez** [comment]
@astaxie thanks for the quick reply! And thanks for the bat! )
