### ISSUE TITLE
Response JSON颜色没变化，无格式化

### ISSUE THREAD

**Issue by tigercallme** [astaxie/bat#18]
![2015-04-20 16 11 35](https://cloud.githubusercontent.com/assets/1182434/7226118/0c1433a2-e778-11e4-8d56-29de0bbfbc1f.png)

返回的JSON格式未有变化，key，value没有颜色，是少加参数了吗？

**Comment by astaxie** [comment]
你是什么系统？bat是最新版本吗？

**Comment by tigercallme** [comment]
我的是Mac OS X 10.9 ,代码是master上的最新代码。

**Comment by astaxie** [comment]
你`go get -u github.com/astaxie/bat`更新一下试试，我感觉你使用的是老版本的bat，因为我让别人系统是10.9的测试过，没有问题，你看下面的这个截图：

![y 6i o h cg 2y4cs992 v](https://cloud.githubusercontent.com/assets/233907/7243995/9d798858-e807-11e4-9297-a3511ce7e188.jpg)

**Comment by tigercallme** [comment]
代码是pull最新的，版本也是0.0.2.  我在centos6.6上也编译了一份，还是如此。
![2015-04-21 18 18 31](https://cloud.githubusercontent.com/assets/1182434/7250268/4b24e970-e853-11e4-9eb1-7a615f3898ef.png)

**Comment by astaxie** [comment]
有点意思，这两个系统我应该都测试过，都是有颜色的。

哦，我看出来了，你的Content-Type不是application/json

**Comment by tigercallme** [comment]
Content-Type 设置 application/json 后，颜色格式化都搞定，多谢~
