### ISSUE TITLE
Provide cross-platform build

### ISSUE THREAD

**Issue by DavidJFelix** [astaxie/bat#38]
Releases seems to only feature a compiled OSX version. It's pretty simple to provide a Windows and Linux version by simply supplying GOOS environment variable at compile time. Let me know if you'd like any help -- I love the utility, but would really like to install it on systems which don't have a Go compiler installed more easily.

Thanks

**Comment by astaxie** [comment]
Good suggestion

**Comment by PaulCapestany** [comment]
@astaxie @DavidJFelix not sure if you guys know about [goxc](https://github.com/laher/goxc), but it lets you easily create cross-platform builds of Go binaries (and will even auto-publish them as Github releases). 

The TL;DR version is that all you should need to do is generate a Github API token for yourself [here](https://github.com/settings/tokens) and then run the following:

```shell
go get -u github.com/laher/goxc
goxc -wc default publish-github -owner=astaxie
goxc -wc default publish-github -repository=bat
goxc -wlc default publish-github -apikey=GITHUB_API_TOKEN
goxc bump 
git commit
git remote push
goxc -bc='linux,!arm windows,darwin'
```

**Comment by astaxie** [comment]
@PaulCapestany wow. That's really convenient. I will do that now. Thanks so much

**Comment by astaxie** [comment]
@DavidJFelix https://github.com/astaxie/bat/releases

**Comment by DavidJFelix** [comment]
Very nice @astaxie, and no @PaulCapestany, I did not know about this tool... I do now! Thanks.

Looking forward to being able to easily provision bat onto my machines.

**Comment by PaulCapestany** [comment]
@astaxie glad you found it useful 👍

**Comment by lucianf** [comment]
Hi @astaxie, any reason why the goxc release is marked 0.0.1 while the main project sits at 0.1.0?  Is this a typo or was the goxc release built from a different branch?
